### ISSUE TITLE
Likes and reactions UX improvements

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#105]
## Generic information
- Application build code: `4200` 
- Reporting user: @lauranori 
- Interested people: @kwunyeung, Rooty

## Context
Currently likes and reactions are thought as completely separate entities and have a totally different way of being used and viewed by the users. 

- **Usage**  
   Likes are added using the :heart: icon, while reactions are added using the :grin: button on each post item. 

- **Post details counter**
   Inside the post details, the likes counter is placed on the bottom of the page, near the like button. For reactions, instead, the counter is put in the tabbed bar in the middle of the screen. 

- **Post details viewing**  
   For likes, it is not possible to view who added them, while for reactions there's a comprehensive list of all users and the related added reaction. 

A part from the UI-related things, likes and reactions are the same thing. A like is only a specific reaction, the red heart: :heart:. 

It would be nice to find a way to solve the depicted problems making so that users are able to use and view everything for both likes and reactions.

**Comment by kwunyeung** [comment]
We better merge the :heart: and other reactions back into a unify UI as they are actually the same thing on chain. This may also be related to the current emoji keyboard as the "Recent" column of the keyboard is always empty on iOS. Users tend to like with :heart: or 👍  or 🤣  and they should be in an easy reach interface.
