### ISSUE TITLE
Mnemonic popup continiously popping up after login with backup

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#106]
## Generic information
- OS name and version: Android/iOS
- Application build code: `4200`
- Network type (mobile/Wi-Fi): Both
- Reporting user: @lauranori 

## Bug description
After logging in with the mnemonic backup, the application keeps telling me to backup the mnemonic phrase. It shouldn't be that way: since I logged in with it, it should be obvious that I have the mnemonic :joy:  

## Steps to reproduce
1. Backup the mnemonic phrase. 
2. Log out. 
3. Log in using the mnemonic phrase. 
4. Perform 5 operations. 

## Expected behavior
After logging in with the mnemonic phrase, the popup should never be viewed.

**Comment by ryuash** [comment]
I guess we can do a check if the user logs in using the the mnemonic phrase then we don't won't display it

**Comment by rmontagnin** [comment]
@ryuash Yeah I think that would be sufficient
