### ISSUE TITLE
Create account flow broken on iOS

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#107]
## Generic information
- OS name and version: iOS
- Application build code: `4200` 
- Network type (mobile/Wi-Fi): Both
- Reporting user: @lauranori 

## Bug description
Inside the login screen, after tapping the "Create account" button using an iOS device it is not possible to come back to the login page. 
This makes it very frustrating for the users who then have to close and re-open the app due to a missing back button.

## Steps to reproduce
1. Open the login screen
2. Tap the "Create a new account" button

## Expected behavior
The user should be able to come back to the login screen after tapping that button. This is to prevent any frustrating app reopening after tapping on such button inadvertently.

**Comment by ryuash** [comment]
@RiccardoM I don't think this was ever an option? I just tried on Android to be sure and pressing the Back button would just leave the app. Going back to the login page would just checked that they are logged in and get redirected to the home screen.

**Comment by rmontagnin** [comment]
@ryuash This is highly related to #108. I think that adding a popup there that can be dismissed and block the account creation might be the best choice to solve also this issue
