### ISSUE TITLE
Heart emoji not being displayed correctly

### ISSUE THREAD

**Issue by ryuash** [desmos-labs/mooncake#139]
## Generic information
- OS name and version: iOS 13.6.1 (17G80)
- Application build code: `4402`
- Network type (mobile/Wi-Fi): Both
- Reported by: @lauranori 

## Bug description
Reactions displaying a black heart instead of the red heart
![image](https://user-images.githubusercontent.com/42913823/91520661-6aeb7180-e928-11ea-82d9-863a952fdf8a.png)

## Steps to reproduce
1. Open the app
2. Like a photo

**Comment by ryuash** [comment]
Unable to reproduce

**Comment by rmontagnin** [comment]
@ryuash Might this be a bug with Apple's system font?

**Comment by ryuash** [comment]
@RiccardoM I'll double check in a bit with an iphone. Will update the status if i can reproduce

**Comment by kwunyeung** [comment]
Not only the heart but all symbols in ASCII table are being displayed as ASCII not unicode emoji. This happens after I updated to `v0.5.0`.

**Comment by rmontagnin** [comment]
@kwunyeung Can we get your iOS version?

**Comment by kwunyeung** [comment]
@RiccardoM iOS 14

**Comment by rmontagnin** [comment]
@ryuash Can you take a look at this please? The code is inside branch `version/0.5.0`

**Comment by kwunyeung** [comment]
Hm... suddenly the emoji is back... 😓

**Comment by rmontagnin** [comment]
@kwunyeung Was it solved in build `5001`?

**Comment by kwunyeung** [comment]
No. I reopen `Mooncake` and they suddenly appear correctly. @ryuash witnessed this. 😅
