### ISSUE TITLE
Loading post is very slow

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/mooncake#23]
Loading list of posts and content of the posts are very slow. This will discourage users to use the application.

**Comment by rmontagnin** [comment]
@kwunyeung could you please provide the following info? 

- Operative system name and version (i.e. `iOS X.Y` or `Android X.Y`)
- Application build code
- Current network speed
- Type of network (Wi-Fi or mobile)

**Comment by kwunyeung** [comment]
#### Operative system name and version (i.e. iOS X.Y or Android X.Y)
iOS 13.5

#### Application build code
~~4001~~ 4004

#### Current network speed
100Mbps

#### Type of network (Wi-Fi or mobile)
Wi-Fi

**Comment by rmontagnin** [comment]
@kwunyeung Could you please update to `4004` and let me know if that version is faster than `4001`?

**Comment by kwunyeung** [comment]
Oops... sorry my bad. It's `4004`. Actually `4004` is even slower than `4001`. And the response of `4004` is more laggy.

**Comment by rmontagnin** [comment]
Should have been fixed with 4abcbe34ef59a0488dd5b5d3c6602a42fde546e4
