### ISSUE TITLE
Differences in the report popup design

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/mooncake#28]
## Generic information
- OS name and version: iOS 13.5
- Application build code: 4004
- Network type (mobile/Wi-Fi): Wi-Fi 

## Bug description

1. Change the colour of the check box icon to `#999999` and the colour of the 
separate lines to `#ECECEC`
2. `Other` is always the last option, change the style of input box
3. Button alignment

## Expected behavior

https://xd.adobe.com/view/a017302b-fd5d-4ad5-481b-19968582ae5f-d626/screen/c2a2acbc-7611-49ea-87d2-a24ea3614062/3-2-report

![report popup](https://user-images.githubusercontent.com/932636/83617961-667b1b00-a5bc-11ea-9b1f-fe7c56bff247.png)

**Comment by rmontagnin** [comment]
Fixed with 792a4bc549048405eb74120174b07ef8e66f0a10 and 7752cdc4d56dcb0d585e8ba693f31475b8dcc188
