### ISSUE TITLE
Messages can't be synced from a new account after several posts

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/mooncake#34]
## Generic information
- OS name and version: iOS 13.6
- Application build code: 4012
- Network type (mobile/Wi-Fi):  WiFi

## Bug description

Can't post new messages from a new account after posting several messags.

The last message sent from this account is

https://morpheus.desmos.network/transactions/3ECC1061CEE22924E2205D1F8F9ECFE8844DC28F0ECAA125CCDBBAB69DF8C328

which is the poll I have tested at #33 

After that the posts can't be synced
![IMG_5056](https://user-images.githubusercontent.com/932636/85503806-16bccc00-b61d-11ea-9f34-63b8983e7be6.jpg)

**Comment by rmontagnin** [comment]
@kwunyeung What error message do you get after long pressing the post?

**Comment by kwunyeung** [comment]
It was `signature verification error`. I can't load that error again as there is no red background in that post now. I keep seeing the app trying to syncing every 30 seconds but the tx is not on chain.

**Comment by rmontagnin** [comment]
@kwunyeung Is this still showing up?

**Comment by kwunyeung** [comment]
No. This issue can be closed.
