### ISSUE TITLE
Posting comment failed 

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/mooncake#4]
I was trying to post comment From device but failed.
![4E8273ED-EC50-4CEE-B2AA-50DAD0A7B565](https://user-images.githubusercontent.com/932636/72658718-1a09b700-39f0-11ea-90be-88a52f9fcfb6.png)

**Comment by rmontagnin** [comment]
I think this was closed in version 0.0.2. Please let me know if this raises again.
