### ISSUE TITLE
Switch CI/CD systems to GitHub Actions

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#41]
Currently our CI system relies on [CircleCI](http://circleci.com/) to build and test the application, and [Travis](https://travis-ci.com/) to build and publish the documentation. 

I honestly think that we might be able to properly switch to the new [GitHub Actions](https://github.com/features/actions) CI/CD system. This wold probably would bring some improvements such as: 

- all the CI/CD will be done in one place, making it easier to check for errors; 
- we would be able to run any kind of job on any OS we want for free; 
- we could be able to integrate new features easily thanks to the existence of many already setup actions inside the [Marketplace](https://github.com/marketplace?type=actions). 

Here are some resource I've found interesting and we might want to look at:

- [CI/CD for Flutter Apps Using GitHub Actions](https://medium.com/better-programming/ci-cd-for-flutter-apps-using-github-actions-b833f8f7aac)
- [GitHub Actions for Flutter App](https://www.linkedin.com/pulse/github-actions-flutter-app-moataz-nabil/)

What do you think about this @ryuash?

**Comment by kwunyeung** [comment]
I've been reading about GitHub Actions recently and it should have a better integration with projects on GitHub. We are also planning to run the frontend of Forbole website directly on GitHub with Actions so that changes on our website frontend can be tracked and deployed easily. The marketplace is quite resourceful.

**Comment by ryuash** [comment]
Let's do it!
