### ISSUE TITLE
Allow to remove a poll from withing the post creation screen

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#58]
## Feature description 
Currently it's not possible to delete a poll once it has been added to the post being created inside the proper screen. We should allow for that. 

## Implementation proposal
Add a button that allows to delete the entire post all together after having added it.

**Comment by ryuash** [comment]
@RiccardoM I don't think adding a button would be good UI
instead i propose we show a toggle indicator that allows the user to turn the poll on and off
<img src="https://user-images.githubusercontent.com/42913823/88139521-6f828300-cc22-11ea-9dd0-b31b9216642d.png" width="300">

**Comment by rmontagnin** [comment]
@ryuash Yup, that seems better!
